function a8_KI_withHole

addr=pwd;
a28_KI_withHole_flowout
cd(addr)
a38_KI_withHole_flowout_generateConcentrationContour
cd(addr)
a48_KI_withHole_flowout_Correction
cd(addr)
a58_AntRegistration_KI_withHole_flowout_T2Corrected